# Generated by Django 4.0.5 on 2022-06-26 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsheet',
            name='examId',
        ),
        migrations.RemoveField(
            model_name='examsheet',
            name='examiner',
        ),
        migrations.AddField(
            model_name='examrequestobject',
            name='requestId',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='examsheet',
            name='exams',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='users.exam'),
            preserve_default=False,
        ),
    ]
